### ISSUE TITLE
Coming soon

### ISSUE THREAD

**Issue by 3kh0** [FogNetwork/Ingot#1]
![image](https://user-images.githubusercontent.com/58097612/191503050-59a9bfc7-adfc-4e9d-93b5-4c5480b6284e.png)

**Comment by Nebelung-Dev** [comment]
It's out now!

**Comment by koproxy** [comment]
For developer options can you use the same tricks to force install extensions? Or force enable flags, etc.

**Comment by 3kh0** [comment]
@koproxy no

**Comment by myf20130** [comment]
@3kh0 do you know the DNS used for jailbreaking chromebooks?

**Comment by 3kh0** [comment]
no

**Comment by myf20130** [comment]
@3kh0 can you goto things proxy server then #dns (discord) and copy it for me?

**Comment by myf20130** [comment]
i would assume you have access to things proxy
