### ISSUE TITLE
developer mode does not work

### ISSUE THREAD

**Issue by 1Scyrus** [FogNetwork/Ingot#4]
developer mode does not enable it in extensions.

**Comment by Awesomeplayer165** [comment]
Yes i agree this does not work.

**Comment by cruncher12** [comment]
@15cyrus If you look at the source, you can see it is switch that (I think) doesn't do anything.

**Comment by rosne-gamingyt** [comment]
> @15cyrus If you look at the source, you can see it is switch that (I think) doesn't do anything. EDIT: I take that back. It shows the ID's of extensions.

Yes, it does not enable developer mode in the actual https://chrome://extensions tab
