### ISSUE TITLE
Wont work

### ISSUE THREAD

**Issue by CheesyPoofs3** [FogNetwork/Ingot#8]
all bookmarklets I have dont work any fix?

**Comment by rosne-gamingyt** [comment]
What is your ChromeOS version. If it is 106 or above, Ingot has **not** been updated to run ChromeOS 106 and above yet.

**Comment by ttvbeghhf** [comment]
How do you check my chrome os version

**Comment by rosne-gamingyt** [comment]
Open the Settings application. Then, click "About ChromeOS" and your version will be right below the Google ChromeOS logo and you will see the version
![Screenshot 2022-10-18 12 57 16 PM](https://user-images.githubusercontent.com/68449858/196496612-b3dc8121-86f7-40da-b369-408a7f4fce86.png)

**Comment by myf20130** [comment]
NO FIX, unless we have another policy bug it wont work
