### ISSUE TITLE
Needs to be updated for ChromeOS 106

### ISSUE THREAD

**Issue by rosne-gamingyt** [FogNetwork/Ingot#9]
My school Chromebook automatically updates to the newest version whenever I shut it down. One day when I turned my Chromebook on, I saw that my enforcement extensions returned. I tried using Ingot to remove it but it was not working and I found out that I recently updated to the newest version. I have no way I have figured out of degrading to ChromeOS 105. So I am requesting for the developers of this project to update it to be compatible with ChromeOS.

From,
Rohan

**Comment by myf20130** [comment]
@rosne-gamingyt NO FIX, unless we have another policy bug it wont work
